repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-yaml
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: trailing-whitespace
      stages: [pre-commit]
