name: Coverage Check

on:
    push:
    pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=./
        coverage report

    - name: Fail if coverage is below threshold
      run: |
        coverage report --fail-under=80
