name: Coverage Check

on:
    pull_request:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install pytest .
        python -m pip install coverage .

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=./

    - name: Fail if coverage is below threshold
      run: |
        coverage report --fail-under=80
