name: Coverage Check

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=./ tests/ > coverage-report.txt

    - name: Comment on Pull Request with Coverage Report
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const coverageReport = fs.readFileSync('coverage-report.txt', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### Python Test Coverage Report:\n\`\`\`\n${coverageReport}\n\`\`\``
          })

    - name: Fail if coverage is below threshold
      run: |
        coverage report --fail-under=80
