name: Python Format

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  format-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Black
      run: |
        pip install black

    - name: Format code with Black
      run: |
        black .

    - name: Save Black output in report file
      run: |
        git diff --exit-code > lint-report.txt || true
        if grep -q "L:" lint-report.txt; then
          echo "black_status=failure" >> $GITHUB_ENV
        else:
          echo "black_status=success" >> $GITHUB_ENV
        fi

    - name: Comment on Pull Request with Black Report
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const lintReport = fs.readFileSync('lint-report.txt', 'utf8');
          const status = process.env.black_status === 'success' ? "✅ Python Lint Passed" : "❌ Python Lint Failed";
          const commentBody = `${status}\n\n### Lint Report:\n\`\`\`\n${lintReport}\n\`\`\``;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: commentBody
          });

    - name: Check for code changes
      run: |
        git diff --exit-code
