name: SQL Lint

on:
  pull_request:

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install SQLFluff
      run: |
        pip install sqlfluff
        pip install sqlfluff-templater-dbt 

    - name: Set DBT Profiles Directory
      run: |
        mkdir -p argentine-exchange-rates-elt/argentine-exchange-rates-elt/dbt/jaffle_shop  # Ajusta esta ruta si es necesario
        echo "DBT_PROFILES_DIR=$(pwd)/argentine-exchange-rates-elt/argentine-exchange-rates-elt/dbt/jaffle_shop" >> $GITHUB_ENV

    - name: Run SQLFluff linting
      run: |
        sqlfluff lint --config .sqlfluff

    - name: Show SQLFluff version
      run: sqlfluff --version
